### ISSUE TITLE
盲水印解码的时候不是应该不需要原图吗？

### ISSUE THREAD

**Issue by okavatar** [ww23/BlindWaterMark#5]
不需要原图解码的水印才叫“盲水印”吧？
你这个文本类型的是盲水印，图像类型的好像不算盲水印了？
以上拙见如有不当请指摘。

**Comment by ww23** [comment]
图片水印不需要原图也可以解码，不过目前不用原图解码效果不是很理想，等优化好了就不需要原图就可以解码了。
至于算不算盲水印，我个人理解盲水印就是人感知不到的水印。
