### ISSUE TITLE
v0.0.3版本中使用离散傅里叶变换编码无效

### ISSUE THREAD

**Issue by QieSen** [ww23/BlindWaterMark#7]
使用离散傅里叶变换编码过程中没有任何错误提示，执行完毕后会输出一张正常图片，图片体积略有增加，但是解码导出的图片中并没有得到正确结果（只有雪花）。
经测试
BlindWatermark-v0.0.3-windows-x86_64.jar
BlindWatermark-v0.0.3-windows-x86_64-gpu.jar
均出现相同情况，其他系统版本未测试。

使用离散余弦变换则可以正常编解码，没有出现问题。

jre版本信息
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

系统版本信息
Windows10 1803 （build 17134.706）

**Comment by ww23** [comment]
DFT 不支持输出的图片格式为 jpg jpeg，输出的时候会丢失水印信息。
